name: Generate HTML

on:
  push:
    branches:
      - main  # Change this to your default branch if it's not 'main'

jobs:
  generate-html:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'

      # - name: Install dependencies
      #   run: |
      #     python -m pip install --upgrade pip
      #     pip install -r requirements.txt  # Ensure you have a requirements.txt file if needed

      - name: Run script
        run: python gen.py  # Replace with the name of your Python script
