name: Generate HTML

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0, 30 * * * *'
  # 每小時的第0和第30分鐘執行

jobs:
  generate-html:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'

      - name: Run script
        run: python gen.py
      - name: Commit and push changes
        run: |
          git config --local user.email "cgshyuankai@proton.me"
          git config --local user.name "Super Lily"
          git add docs/
          git commit -m "Update generated HTML files" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
